# Generated by Django 3.0.8 on 2020-07-12 06:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_hint.typehint


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.GenericIPAddressField(null=True, validators=[django.core.validators.validate_ipv46_address])),
                ('version', models.CharField(max_length=10)),
                ('custom_data', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, django_hint.typehint.StandardModelType),
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=(models.Model, django_hint.typehint.StandardModelType),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('custom_data', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, django_hint.typehint.StandardModelType),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('fatal', 'Fatal'), ('debug', 'Debug'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('stacktrace', models.TextField(null=True)),
                ('custom_data', models.TextField(null=True)),
                ('archived', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Agent')),
            ],
            bases=(models.Model, django_hint.typehint.StandardModelType),
        ),
        migrations.AddField(
            model_name='agent',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='api.Environment'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='api.User'),
        ),
    ]
