# Generated by Django 3.0.8 on 2020-07-18 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200717_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Agent'),
        ),
    ]
