# Generated by Django 3.0.8 on 2020-07-19 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200719_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='event_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='api.EventUser'),
        ),
    ]
